# fly.toml app configuration file generated for yeh35-blog-system on 2024-08-19T14:46:27+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yeh35-blog-system'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[env]
  PHX_SERVER = true
  PHX_HOST = 'yeh35.com'
  PORT = 4000